default:
  image: 'cimg/node:20.18.0'

cache:
  key:
      files:
          - package-lock.json
  paths:
      - './node_modules'

stages:
  - install
  - build
  - lint
  - test

install_dependencies:
  stage: install
  script:
    - npm ci

build:
  stage: build
  script:
    - npm run build

lint:
  stage: lint
  script:
    - npm run lint

unit_tests:
  stage: test
  script:
    - npm run test:unit

release:
  stage: release
  script: # update this to reuse above steps
    - npm ci
    - npm run build 
    - npm run test:unit  
    - echo "//registry.npmjs.org/:_authToken=$TOKEN" > ~/.npmrc
    - npm publish # can add --dry-run flag for testing
    - rm -f ~/.npmrc
  rules:
    # Only run the release step for Git tags (e.g., v1.0.0)
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*/
  when: manual 