default:
  image: 'cimg/node:20.18.0'

stages:
  - install
  - build
  - lint
  - test

variables:
  NODE_VERSION: "20"
  CI_NODEJS_VERSION: $NODE_VERSION

build:
  stage: build
  script:
    - npm run build

lint:
  stage: lint
  script:
    - npm run lint

unit_tests:
  stage: test
  script:
    - npm run test:unit

