stages:
  - install
  - build
  - lint
  - test

variables:
  NODE_VERSION: "20"
  CI_NODEJS_VERSION: $NODE_VERSION

before_script:
  - echo "Installing Node.js $CI_NODEJS_VERSION"
  - curl -sL https://deb.nodesource.com/setup_$CI_NODEJS_VERSION.x | bash -
  - apt-get install -y nodejs
  - node -v
  - npm -v
  - npm ci

build:
  stage: build
  script:
    - npm run build

lint:
  stage: lint
  script:
    - npm run lint

unit_tests:
  stage: test
  script:
    - npm run test:unit

